### ISSUE TITLE
Home button leads back to a broken page

### ISSUE THREAD

**Issue by ar-ray0111** [ElixirTechCommunity/salon#2]

**Comment by Lo-rraine** [comment]
Hi @IshaanTyagi 
I really like how the website looks and  I would love to help out with task. May you assign it to me

**Comment by deepanshu-sharmaa** [comment]
hey @ar-ray0111 can you assign me this issue?

**Comment by Vedanty5501** [comment]
Can you assign this to me. I would really like to help.

**Comment by IshaanTyagi** [comment]
@Vedanty5501 you can work on this issue 🚀

**Comment by IshaanTyagi** [comment]
@deepanshu-sharmaa @Lo-rraine you can look into other issues also to contribute
